//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedGraph {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ZedGraphStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ZedGraphStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZedGraph.ZedGraphStrings", typeof(ZedGraphStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Image copied to clipboard 的本地化字符串。
        /// </summary>
        internal static string copied_to_clip {
            get {
                return ResourceManager.GetString("copied_to_clip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        internal static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page Setup... 的本地化字符串。
        /// </summary>
        internal static string page_setup {
            get {
                return ResourceManager.GetString("page_setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print... 的本地化字符串。
        /// </summary>
        internal static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Image As... 的本地化字符串。
        /// </summary>
        internal static string save_as {
            get {
                return ResourceManager.GetString("save_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Scale to Default 的本地化字符串。
        /// </summary>
        internal static string set_default {
            get {
                return ResourceManager.GetString("set_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Point Values 的本地化字符串。
        /// </summary>
        internal static string show_val {
            get {
                return ResourceManager.GetString("show_val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title 的本地化字符串。
        /// </summary>
        internal static string title_def {
            get {
                return ResourceManager.GetString("title_def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo All Zoom/Pan 的本地化字符串。
        /// </summary>
        internal static string undo_all {
            get {
                return ResourceManager.GetString("undo_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Un-Pan 的本地化字符串。
        /// </summary>
        internal static string unpan {
            get {
                return ResourceManager.GetString("unpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo Scroll 的本地化字符串。
        /// </summary>
        internal static string unscroll {
            get {
                return ResourceManager.GetString("unscroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Un-Zoom 的本地化字符串。
        /// </summary>
        internal static string unzoom {
            get {
                return ResourceManager.GetString("unzoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X Axis 的本地化字符串。
        /// </summary>
        internal static string x_title_def {
            get {
                return ResourceManager.GetString("x_title_def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Y Axis 的本地化字符串。
        /// </summary>
        internal static string y_title_def {
            get {
                return ResourceManager.GetString("y_title_def", resourceCulture);
            }
        }
    }
}
